"""initial

Revision ID: a897b7a344ca
Revises: 
Create Date: 2020-10-30 11:13:52.987084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a897b7a344ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('enable_sign', sa.Boolean(), nullable=True),
    sa.Column('sign_text', sa.String(length=250), nullable=True),
    sa.Column('enable_counter', sa.Boolean(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('scheduler_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wallpapers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('unique_id', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('custom_sign', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_wallpapers_id'), 'wallpapers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallpapers_id'), table_name='wallpapers')
    op.drop_table('wallpapers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
